In [64]:
import pandas as pd

import re
from nltk import SnowballStemmer, sent_tokenize,word_tokenize


def tokenize_and_stem(text):
        # Tokenize by sentence, then by word

        stemmer = SnowballStemmer("english")
        tokens = [word for sent in sent_tokenize(text) for word in word_tokenize(sent)]

        # Filter out raw tokens to remove noise
        filtered_tokens = [token for token in tokens if re.search('[a-zA-Z]', token)]
        # print('filtered tokens ')
        # print(filtered_tokens)

        # Stem the filtered_tokens
        stems = [stemmer.stem(word) for word in filtered_tokens]

        return stems
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer


def setup( *args):
        for arg in args:
            if 'query' not in db:
                db['query'] = ''
            db['query'] += (db[arg].astype(str)+'\n')
            
        # print(db['query'].isnull().sum())  # Check if there are NaN values
        # print((db['query'] == '').sum()) 
        # print(self.db['query'])
        tfidf_vectorizer = TfidfVectorizer(max_df=0.8, max_features=200000,
                                           min_df=0.1, stop_words='english',
                                    tokenizer=tokenize_and_stem,
                                           ngram_range=(1, 3))

        # db.drop_duplicates(subset='name', inplace=True)
        tfidf_matrix = tfidf_vectorizer.fit_transform([x for x in db['query']])
        print(tfidf_matrix)
        similarity_distance = 1 - cosine_similarity(tfidf_matrix)
        print(cosine_similarity(tfidf_matrix))
        # cosine_sim_df = pd.DataFrame(similarity_distance, index=db['name'], columns=db['name'])
        # print(db['name'].duplicated().sum())


        return similarity_distance
import numpy as np


def find_ksimilar(title: str, k, titleCol,similarity_distance):
        index = db[db[titleCol].str.lower() == title.lower()]
        # print(self.db[self.db[titleCol].str.lower() == title.lower()])
        # print(index)
        index = db[db[titleCol].str.lower() == title.lower()].index[0]
        # print(index)
        vector = similarity_distance[index]
    
        print(vector)
        most_similar = db.iloc[np.argsort(vector)[1:k + 1], 1]
        return most_similar

db = pd.read_csv('./datasets/automation_recipes1.csv')
dbPath = './datasets/automation_recipes1.csv'
similarity_dist = setup('name')
print(find_ksimilar('Noodles with Tofu', 10,'name',similarity_dist))

/Users/seymour-butts/miniconda3/lib/python3.12/site-packages/sklearn/feature_extraction/text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
/Users/seymour-butts/miniconda3/lib/python3.12/site-packages/sklearn/feature_extraction/text.py:408: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['abov', 'afterward', 'alon', 'alreadi', 'alway', 'ani', 'anoth', 'anyon', 'anyth', 'anywher', 'becam', 'becaus', 'becom', 'befor', 'besid', 'cri', 'describ', 'dure', 'els', 'elsewher', 'empti', 'everi', 'everyon', 'everyth', 'everywher', 'fifti', 'forti', 'henc', 'hereaft', 'herebi', 'howev', 'hundr', 'inde', 'mani', 'meanwhil', 'moreov', 'nobodi', 'noon', 'noth', 'nowher', 'onc', 'onli', 'otherwis', 'ourselv', 'perhap', 'pleas', 'sever', 'sinc', 'sincer', 'sixti', 'someon', 'someth', 'sometim', 'somewher', 'themselv', 'thenc', 'thereaft', 'therebi', 'therefor', 'to

  (1, 0)	1.0
  (5, 0)	1.0
  (10, 0)	1.0
  (11, 0)	1.0
  (12, 0)	1.0
  (34, 0)	1.0
  (40, 0)	1.0
  (52, 0)	1.0
  (53, 0)	1.0
  (60, 0)	1.0
  (104, 0)	1.0
  (108, 0)	1.0
  (109, 0)	1.0
  (112, 0)	1.0
  (122, 0)	1.0
  (133, 0)	1.0
  (142, 0)	1.0
  (162, 0)	1.0
  (163, 0)	1.0
  (170, 0)	1.0
  (171, 0)	1.0
  (173, 0)	1.0
  (192, 0)	1.0
  (193, 0)	1.0
  (195, 0)	1.0
  :	:
  (30532, 0)	1.0
  (30561, 0)	1.0
  (30563, 0)	1.0
  (30565, 0)	1.0
  (30570, 0)	1.0
  (30621, 0)	1.0
  (30623, 0)	1.0
  (30625, 0)	1.0
  (30626, 0)	1.0
  (30627, 0)	1.0
  (31348, 0)	1.0
  (31349, 0)	1.0
  (31350, 0)	1.0
  (32189, 0)	1.0
  (32534, 0)	1.0
  (32560, 0)	1.0
  (32682, 0)	1.0
  (34385, 0)	1.0
  (34663, 0)	1.0
  (34699, 0)	1.0
  (34712, 0)	1.0
  (34718, 0)	1.0
  (34727, 0)	1.0
  (34739, 0)	1.0
  (34800, 0)	1.0
[[0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[1. 1. 1. ... 1. 1. 1.]
23260                     